### ISSUE TITLE
docker执行了怎么感觉没反应啊，前端的ADH没有查询记录

### ISSUE THREAD

**Issue by mrzj110** [kkkgo/PaoPao-Pref#1]

**Comment by kkkgo** [comment]
如果在docker中运行，你需要指定-server指定DNS服务器。你可以加上-v来查看运行日志。

**Comment by mrzj110** [comment]
![QQ截图20230422102020](https://user-images.githubusercontent.com/43603971/233756898-3fcaeebe-0541-41c6-9b88-9d9ff39a3def.png)

**Comment by mrzj110** [comment]
> 如果在docker中运行，你需要指定-server指定DNS服务器。你可以加上-v来查看运行日志。

指定了的，用Debian怎么使用啊

**Comment by mrzj110** [comment]
> 如果在docker中运行，你需要指定-server指定DNS服务器。你可以加上-v来查看运行日志。

指定了的，我用Windows可以了

**Comment by kkkgo** [comment]
用新镜像吧，支持设置环境变量和更多参数。

**Comment by kkkgo** [comment]
新镜像使用了内建的nslookup，速度更快。
