### ISSUE TITLE
在docker添加命令-v执行了，log再哪儿看？

### ISSUE THREAD

**Issue by simon-yanghl** [kkkgo/PaoPao-Pref#3]
用命令
docker run --rm -it sliamb/paopao-pref -server 10.10.10.2 -pc 100 -limit 3000 -sleep 0ms -timeout 1s -v yes
执行，163.46秒完成，想看看具体性能和LOG应该在哪里查看？

**Comment by kkkgo** [comment]
你在终端执行过程中就会输出log。

**Comment by simon-yanghl** [comment]
> 你在终端执行过程中就会输出log。

明白，那执行完之后有总结文件么？还是只有屏幕输出？

**Comment by kkkgo** [comment]
只有屏幕输出，参考ReadMe的测试指标

**Comment by kkkgo** [comment]
输出的可参考指标：
运行过程中/结束后 均可参考成功率 `Succ rate`和域名平均处理时间 `Avg time`
结束后可参考处理总时间。

**Comment by simon-yanghl** [comment]
> 只有屏幕输出，参考ReadMe的测试指标

好的。我最近一次运行的结果是
Percentage : 100 %
Total Line : 849264
Concurrency Limit: 3000
Timeout: 1s
Sleep: 0s
DNS Server: 10.10.10.2
DNS Port: 53
Nslookup 849264/849264 domains[100.0000%]. Succ rate:2.01%. Avg time: 0.000206 seconds. Est time: 00:00:00.
Done. Processed 849264/849264 domains in 175.63 seconds.

命中率是不是太低了……

**Comment by kkkgo** [comment]
设备性能和网络性能处理不过来成功率就会低。
你可以适当调高/调低limit,sleep和timeout的值。
